# zshrc by @windvalley
# https://raw.githubusercontent.com/windvalley/work-efficiency-utils/master/zsh/zshrc


# vim: set foldmarker={{,}} foldlevel=0 foldmethod=marker:
#
# NOTE:
#   查看折叠内容的方法:
#      za: normal 模式下按 za , 表示当光标在关闭折叠上时打开之, 在打开折叠上时关闭之;
#          在打开的折叠内部任意处按 za , 也会关闭折叠.
#      zA: 是 za 的递归操作, 是针对嵌套折叠的场景.


# --- 安装步骤 {{

#   1. 安装 ohmyzsh
#      doc: https://github.com/ohmyzsh/ohmyzsh
#      sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
#      主题所在目录:
#      ls ~/.oh-my-zsh/themes
#      插件所在目录:
#      ls ~/.oh-my-zsh/plugins
#
#   2. 常用插件安装
#      doc: https://github.com/unixorn/awesome-zsh-plugins
#      1) 自动补全插件:
#      cd ~/.oh-my-zsh/plugins
#      git clone git://github.com/zsh-users/zsh-autosuggestions
#      2) 语法高亮插件:
#      git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
#      3) 目录智能跳转命令 z 安装:
#      brew install autojump
#
#   3. 使用本 zshrc 文件
#      wget -O ~/.zshrc https://raw.githubusercontent.com/windvalley/work-efficiency-utils/master/zsh/zshrc

# }}


# --- 基础配置 {{

# oh-my-zsh 安装路径.
export ZSH="$HOME/.oh-my-zsh"

# 推荐的主题列表: ys, robbyrussell, amuse, agnoster, random
# doc: https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="ys"

# 标准插件存放在: $ZSH/plugins/
# 定制插件存放在: $ZSH_CUSTOM/plugins/
# NOTE: z 命令依赖 autojump 包, brew install autojump.
plugins=(git zsh-autosuggestions z brew extract)

source $ZSH/oh-my-zsh.sh

export LANG=en_US.UTF-8

# 解决执行 crontab -e 报错的问题.
export EDITOR=vim

# 命令行颜色高亮.
source $HOME/.zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# }}


# --- 代理配置 {{

# 为终端设置使用 ShadowsocksX 提供的 HTTP 代理快捷命令.
# NOTE:
# 需要先启动 ShadowsocksX 软件, 配置好代理服务器, 选择'自动模式'和'启用HTTP代理' 即可;
# 每个终端标签页想使用代理, 都需要先执行 proxy, 然后 curl google.com 进行测试;
# 关闭当前标签页的代理, 使用 unproxy 命令.
alias proxy="export http_proxy=http://127.0.0.1:1081 https_proxy=http://127.0.0.1:1081"
alias unproxy="unset http_proxy https_proxy"

# brew 资源镜像配置, 使用代理的时候不使用此资源镜像.
[[ -z "http_proxy" ]] &&
    export HOMEBREW_BOTTLE_DOMAIN=https://mirrors.ustc.edu.cn/homebrew-bottles

# }}


# --- 编程语言 {{

# ****** Go ******
GOPATH=$HOME/go
GOBIN=$GOPATH/bin
GOPROXY=https://goproxy.cn
PATH="$GOBIN:$PATH"
export GOPATH GOBIN GOPROXY PATH

alias gf=gf
# ****************

# ****** Python3 ******
export PATH="/usr/local/opt/python3/bin:$PATH"
ln -sf /usr/local/opt/python3/bin/python3 /usr/local/opt/python3/bin/python

# poetry
export PATH="$HOME/.poetry/bin:$PATH"
# *********************

# ****** Lua ******
# lua 指定使用 5.3 版本.
ln -sf /usr/local/Cellar/lua/5.3.5_1/bin/lua /usr/local/bin/lua
# luarocks 指定使用 lua 的 5.3 版本.
alias luarocks="luarocks  --lua-dir=/usr/local/opt/lua@5.3"
export PATH=$HOME/.luarocks/bin:$PATH
# *****************

# }}


# --- 其他配置 {{

# ****** tmux ******
alias tls="tmux ls"

# 以下 alias 对 session 名称是个位数字的情况无效.
alias tnew="tmux new -s "
alias trename="tmux rename-session -t "
alias ta="tmux attach -t "
alias tkill="tmux kill-session -t "
# ******************


# usage: history -100
alias history="history -i"

# 列出正在监听的tcp连接.
alias lsof_tcp="lsof -aP -i TCP -s TCP:LISTEN"

export GPG_TTY=$(tty)

# }}


# --- 使用技巧 {{

#           ctrl f  输入任意命令行的一部分时, 如果自动出现补全提示,
#                   使用此快捷键自动采纳提示的补全信息.
#              tab  命令行输入一部分后按 tab 键触发补全提示或在提示项中选择.
#           ctrl g  取消选择 tab 选择的补全提示项, 回到命令行本身.
#                z  z 后输入你要切换的目标目录的一部分, 回车即可自动跳转到目标目录.

# }}
